# 运行与环境
run:
  experiment_name: "ddpm_gmm_demo"
  output_dir: "runs"               # TensorBoard 与检查点目录
  seed: 42
  device: "auto"                   # "auto"|"cpu"|"cuda"
  cudnn:
    benchmark: false
    deterministic: true

# 数据集（合成）
data:
  name: "gmm"                       # "gmm" | "ring"
  num_samples: 10000
  batch_size: 512
  num_workers: 0
  gmm:
    num_modes: 8
    radius: 4.0
    std: 0.15
  ring:
    radius: 4.0
    noise_std: 0.05

# Diffusion（DDPM）
diffusion:
  timesteps: 200
  beta_schedule: "linear"           # "linear" | "cosine"
  beta_start: 1.0e-4
  beta_end: 2.0e-2

# 模型（MLP 噪声预测器）
model:
  input_dim: 2
  hidden_dim: 128
  num_layers: 3
  time_embed_dim: 32

# 训练
train:
  epochs: 50
  lr: 1.0e-3
  weight_decay: 0.0
  grad_clip: 1.0
  log_interval: 50
  ckpt_interval: 10
  sample_interval: 5
  sample_size: 2048

# 追踪与日志
tracking:
  tensorboard: true
  mlflow:
    enabled: false
    tracking_uri: "file:./mlruns"
    experiment_name: "ddpm_gmm_demo"
